# Generated by Django 5.2.14 on 2026-05-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
           field=models.TimeField(default='10:00:00'),
            preserve_default=False,
        ),
    ]
